name: Dummy Wait Job

on:
  pull_request:

jobs:
  wait_and_pass:
    runs-on: ubuntu-latest
    name: test-rules
    steps:
      - name: Wait 1 minute
        run: sleep 60

      - name: Mark as success
        run: echo "✅ Dummy job finished successfully"
